# Generated by Django 6.0.7 on 2026-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='assets/images/category-thumb-1.jpg', max_length=255),
        ),
    ]
