# Generated by Django 6.0.7 on 2026-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product image', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(blank=True, help_text='Date the product was manufactured', null=True),
        ),
    ]
