# Generated by Django 6.0.7 on 2026-08-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
